# Site settings
author: zhiqiang
title: test
header-img: img/home-bg.png
email: sunzhiqiang04@gmail.com
copyright_name: zhiqiang
description: > # this means to ignore newlines until "baseurl:"
  shortest
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  sachenl

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
